services:
    twitch_api.client:
        class: Twitch\ApiBundle\Service\TwitchClientService
        arguments:
            - "@monolog.logger"
            - "%twitch_api.client.id%"
            - "%twitch_api.client.secret%"
